server:
  port: 1111
spring:
  application:
    name: eureka
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@localhost:1111/eureka
